import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import '@ant-design/v5-patch-for-react-19';
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
        <ToastContainer position={"bottom-left"} autoClose={3000}/>
      </body>
    </html>
  );
}
